### ISSUE TITLE
How does it work confusion

### ISSUE THREAD

**Issue by idontgetoutmuch** [thomasjm/julia2nix#13]
I read the documentation but I don't know why I still need the toml files.

```
dom@MacBook-Pro depot1 % o$(nix-build -I nixpkgs=/Users/dom/nixpkgs . --no-out-link)/bin/julia
$(nix-build -I nixpkgs=/Users/dom/nixpkgs . --no-out-link)/bin/julia
error: getting attributes of path '/Users/dom/Dropbox/Tidy/depot1/Manifest.toml': No such file or directory
(use '--show-trace' to show detailed location information)
zsh: no such file or directory: /bin/julia
dom@MacBook-Pro depot1 % $(nix-build -I nixpkgs=/Users/dom/nixpkgs . --no-out-link)/bin/julia
$(nix-build -I nixpkgs=/Users/dom/nixpkgs . --no-out-link)/bin/julia
error: getting attributes of path '/Users/dom/Dropbox/Tidy/depot1/Project.toml': No such file or directory
(use '--show-trace' to show detailed location information)
zsh: no such file or directory: /bin/julia
dom@MacBook-Pro depot1 % $(nix-build -I nixpkgs=/Users/dom/nixpkgs . --no-out-link)/bin/julia
$(nix-build -I nixpkgs=/Users/dom/nixpkgs . --no-out-link)/bin/julia
trace: Warning: `stdenv.lib` is deprecated and will be removed in the next release. Please use `lib` instead. For more information see https://github.com/NixOS/nixpkgs/issues/108938
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.3 (2020-11-09)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

```

**Comment by GTrunSec** [comment]
Do I need to write a devShell for newbie users to julia2nix frendly?

**Comment by idontgetoutmuch** [comment]
I was a bit suspicious that I had done something wrong and that
somehow julia was just using the toml and not using nix. Looking at
the output below, it still feels like that is what is happening
though.

```
julia> using Distributions
using Distributions
ERROR: ArgumentError: Package Distributions not found in current path:
- Run `import Pkg; Pkg.add("Distributions")` to install the Distributions package.

julia> pkg"status"
pkg"status"
Status `~/.julia/environments/v1.5/Project.toml` (empty project)

julia> pkg"activate ."
pkg"activate ."
 Activating environment at `~/Dropbox/Tidy/depot/Project.toml`

julia> using Distributions
using Distributions

julia> pkg"status"
pkg"status"
Status `~/Dropbox/Tidy/depot/Project.toml`
  [31c24e10] Distributions v0.24.14
```

**Comment by idontgetoutmuch** [comment]
> Do I need to write a devShell for newbie users to julia2nix frendly?

@GTrunSec if you mean me, I am not sure. What would a `devShell` do?

**Comment by GTrunSec** [comment]
the devShell just help your https://github.com/GTrunSec/my-julia2nix-env/blob/main/shell.nix to use direnv or some commands easily.

**Comment by idontgetoutmuch** [comment]
> first, modify `{ pkgs ? import <nixpkgs>) { } }` to `{ pkgs ? import (import <your local-nixpkgs path>") { } }: ` in `default.nix `
> 
> second, make sure you have done to generated packages.nix with `julia2nix`
> 
> third, run `$(nix-build . --no-out-link)/bin/julia` to enter julia

I have `$(nix-build -I nixpkgs=/Users/dom/nixpkgs . --no-out-link)/bin/julia` which should do the same?

**Comment by idontgetoutmuch** [comment]
> 
> please, check `ENV` first, make sure you got DEPOT_PATH as following:
> 
> ```
> "JULIA_DEPOT_PATH"       => "./.julia_depot:/nix/store/w7rzd4jvhcr60j3fgy9j148vmzbhjs5f-julia-depot"
> ```

I have
`"JULIA_DEPOT_PATH"        => "/Users/dom/.julia:/nix/store/pcsy2x5wivay4fhzk2gm6qiggq29pds6-julia-depot"`
so it looks like it is working :-) thanks for your help

**Comment by idontgetoutmuch** [comment]
I think we can close this.
