### ISSUE TITLE
Shallow clone for registry

### ISSUE THREAD

**Issue by colinxs** [thomasjm/julia2nix#19]
A deep clone of the General registry can take quite some time. I think its safe to do a shallow clone as follows:

```
    repo = Repo.clone_from(general_repo_url, local_registry_path, depth=1)
```

**Comment by thomasjm** [comment]
You're right, that should be much better. Just need to do a smoke check and then I'll push that. Thanks!

**Comment by thomasjm** [comment]
Done in c294458759dfdc2d90674bfe8779649ebb9f5ed6
